-- Core Oracle schema for the Smart Hall and Roommate Matching Management System
-- This file lays the foundation for authentication, hall management, seat tracking,
-- booking requests, and roommate preference data.

CREATE TABLE app_user (
    user_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    full_name         VARCHAR2(100) NOT NULL,
    email             VARCHAR2(120) NOT NULL UNIQUE,
    password_hash     VARCHAR2(255) NOT NULL,
    role_name         VARCHAR2(20) NOT NULL,
    department        VARCHAR2(80),
    monthly_budget    NUMBER(10, 2),
    gender            VARCHAR2(20),
    is_quiet          CHAR(1) DEFAULT 'N' CHECK (is_quiet IN ('Y', 'N')),
    status            VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_user_role CHECK (role_name IN ('STUDENT', 'HALL_ADMIN', 'ADMIN')),
    CONSTRAINT chk_user_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'ARCHIVED'))
);

CREATE TABLE hall (
    hall_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    hall_name         VARCHAR2(120) NOT NULL UNIQUE,
    location          VARCHAR2(180) NOT NULL,
    capacity          NUMBER NOT NULL CHECK (capacity >= 0),
    description       VARCHAR2(500),
    status            VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_hall_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE'))
);

CREATE TABLE room (
    room_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    hall_id           NUMBER NOT NULL,
    room_number       VARCHAR2(30) NOT NULL,
    room_type         VARCHAR2(30) DEFAULT 'STANDARD' NOT NULL,
    capacity          NUMBER NOT NULL CHECK (capacity > 0),
    rent_amount       NUMBER(10, 2) DEFAULT 0 NOT NULL,
    room_status       VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,
    remarks           VARCHAR2(500),
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_room_hall FOREIGN KEY (hall_id) REFERENCES hall (hall_id),
    CONSTRAINT uq_room_number_per_hall UNIQUE (hall_id, room_number),
    CONSTRAINT chk_room_status CHECK (room_status IN ('AVAILABLE', 'PARTIAL', 'FULL', 'MAINTENANCE'))
);

CREATE TABLE seat (
    seat_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    room_id           NUMBER NOT NULL,
    seat_label        VARCHAR2(20) NOT NULL,
    seat_status       VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,
    current_student_id NUMBER,
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_seat_room FOREIGN KEY (room_id) REFERENCES room (room_id),
    CONSTRAINT fk_seat_student FOREIGN KEY (current_student_id) REFERENCES app_user (user_id),
    CONSTRAINT uq_seat_per_room UNIQUE (room_id, seat_label),
    CONSTRAINT chk_seat_status CHECK (seat_status IN ('AVAILABLE', 'PENDING', 'BOOKED', 'BLOCKED'))
);

CREATE TABLE roommate_preference (
    preference_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    student_id        NUMBER NOT NULL UNIQUE,
    preferred_department VARCHAR2(80),
    budget_min        NUMBER(10, 2),
    budget_max        NUMBER(10, 2),
    preferred_gender  VARCHAR2(20),
    prefers_quiet_room CHAR(1) DEFAULT 'N' CHECK (prefers_quiet_room IN ('Y', 'N')),
    smoking_allowed   CHAR(1) DEFAULT 'N' CHECK (smoking_allowed IN ('Y', 'N')),
    sleep_schedule    VARCHAR2(80),
    study_habit       VARCHAR2(80),
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_pref_student FOREIGN KEY (student_id) REFERENCES app_user (user_id)
);

CREATE TABLE booking_request (
    request_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    student_id        NUMBER NOT NULL,
    hall_id           NUMBER NOT NULL,
    room_id           NUMBER NOT NULL,
    seat_id           NUMBER NOT NULL,
    request_status    VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    requested_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    reviewed_by       NUMBER,
    reviewed_at       TIMESTAMP,
    remarks           VARCHAR2(500),
    CONSTRAINT fk_request_student FOREIGN KEY (student_id) REFERENCES app_user (user_id),
    CONSTRAINT fk_request_hall FOREIGN KEY (hall_id) REFERENCES hall (hall_id),
    CONSTRAINT fk_request_room FOREIGN KEY (room_id) REFERENCES room (room_id),
    CONSTRAINT fk_request_seat FOREIGN KEY (seat_id) REFERENCES seat (seat_id),
    CONSTRAINT fk_request_reviewer FOREIGN KEY (reviewed_by) REFERENCES app_user (user_id),
    CONSTRAINT chk_request_status CHECK (request_status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'))
);

CREATE TABLE booking_history (
    history_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    request_id        NUMBER NOT NULL,
    action_type       VARCHAR2(30) NOT NULL,
    action_by         NUMBER NOT NULL,
    action_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    notes             VARCHAR2(500),
    CONSTRAINT fk_history_request FOREIGN KEY (request_id) REFERENCES booking_request (request_id),
    CONSTRAINT fk_history_action_by FOREIGN KEY (action_by) REFERENCES app_user (user_id)
);

CREATE INDEX idx_room_hall_status ON room (hall_id, room_status);
CREATE INDEX idx_seat_room_status ON seat (room_id, seat_status);
CREATE INDEX idx_booking_request_status ON booking_request (request_status);
CREATE INDEX idx_student_role ON app_user (role_name);

CREATE OR REPLACE VIEW v_seat_availability AS
SELECT
    h.hall_id,
    h.hall_name,
    r.room_id,
    r.room_number,
    r.capacity,
    COUNT(s.seat_id) AS total_seats,
    SUM(CASE WHEN s.seat_status = 'AVAILABLE' THEN 1 ELSE 0 END) AS available_seats,
    SUM(CASE WHEN s.seat_status = 'BOOKED' THEN 1 ELSE 0 END) AS booked_seats,
    SUM(CASE WHEN s.seat_status = 'PENDING' THEN 1 ELSE 0 END) AS pending_seats
FROM hall h
JOIN room r ON r.hall_id = h.hall_id
JOIN seat s ON s.room_id = r.room_id
GROUP BY h.hall_id, h.hall_name, r.room_id, r.room_number, r.capacity;
