-- ==============================================================
-- NestSync - Smart Hall & Roommate Matching Management System
-- Step 1: Core schema (Oracle SQL)
-- ==============================================================
-- This script creates the six required tables:
-- USERS, HALLS, ROOMS, SEATS, BOOKINGS, ROOMMATE_MATCHES
--
-- Run order:
-- 1) 01_core_schema.sql
-- 2) 02_roommate_matching.sql (sample data)

CREATE TABLE users (
    user_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    full_name          VARCHAR2(120) NOT NULL,
    email              VARCHAR2(150) NOT NULL,
    password_hash      VARCHAR2(255) NOT NULL,
    role_name          VARCHAR2(20) NOT NULL,
    department         VARCHAR2(80),
    monthly_budget     NUMBER(10,2),
    preferences_text   VARCHAR2(300),
    account_status     VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_users_role CHECK (role_name IN ('STUDENT', 'HALL_ADMIN', 'SYSTEM_ADMIN')),
    CONSTRAINT chk_users_status CHECK (account_status IN ('ACTIVE', 'INACTIVE', 'BLOCKED'))
);

CREATE TABLE halls (
    hall_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    hall_name          VARCHAR2(120) NOT NULL,
    hall_location      VARCHAR2(180) NOT NULL,
    total_capacity     NUMBER NOT NULL,
    managed_by_admin   NUMBER,
    created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_halls PRIMARY KEY (hall_id),
    CONSTRAINT uq_halls_name UNIQUE (hall_name),
    CONSTRAINT fk_halls_admin FOREIGN KEY (managed_by_admin) REFERENCES users(user_id),
    CONSTRAINT chk_halls_capacity CHECK (total_capacity >= 0)
);

CREATE TABLE rooms (
    room_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    hall_id            NUMBER NOT NULL,
    room_number        VARCHAR2(30) NOT NULL,
    room_type          VARCHAR2(30) DEFAULT 'STANDARD' NOT NULL,
    monthly_rent       NUMBER(10,2) DEFAULT 0 NOT NULL,
    room_status        VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,
    CONSTRAINT pk_rooms PRIMARY KEY (room_id),
    CONSTRAINT fk_rooms_hall FOREIGN KEY (hall_id) REFERENCES halls(hall_id),
    CONSTRAINT uq_rooms_hall_room UNIQUE (hall_id, room_number),
    CONSTRAINT chk_rooms_status CHECK (room_status IN ('AVAILABLE', 'PARTIAL', 'FULL', 'MAINTENANCE'))
);

CREATE TABLE seats (
    seat_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    room_id            NUMBER NOT NULL,
    seat_label         VARCHAR2(20) NOT NULL,
    seat_status        VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,
    current_student_id NUMBER,
    CONSTRAINT pk_seats PRIMARY KEY (seat_id),
    CONSTRAINT fk_seats_room FOREIGN KEY (room_id) REFERENCES rooms(room_id),
    CONSTRAINT fk_seats_student FOREIGN KEY (current_student_id) REFERENCES users(user_id),
    CONSTRAINT uq_seats_room_label UNIQUE (room_id, seat_label),
    CONSTRAINT chk_seats_status CHECK (seat_status IN ('AVAILABLE', 'PENDING', 'BOOKED', 'BLOCKED'))
);

CREATE TABLE bookings (
    booking_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    student_id         NUMBER NOT NULL,
    hall_id            NUMBER NOT NULL,
    room_id            NUMBER NOT NULL,
    seat_id            NUMBER NOT NULL,
    booking_status     VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    requested_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    reviewed_by        NUMBER,
    reviewed_at        TIMESTAMP,
    notes              VARCHAR2(300),
    CONSTRAINT pk_bookings PRIMARY KEY (booking_id),
    CONSTRAINT fk_bookings_student FOREIGN KEY (student_id) REFERENCES users(user_id),
    CONSTRAINT fk_bookings_hall FOREIGN KEY (hall_id) REFERENCES halls(hall_id),
    CONSTRAINT fk_bookings_room FOREIGN KEY (room_id) REFERENCES rooms(room_id),
    CONSTRAINT fk_bookings_seat FOREIGN KEY (seat_id) REFERENCES seats(seat_id),
    CONSTRAINT fk_bookings_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(user_id),
    CONSTRAINT chk_bookings_status CHECK (booking_status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'))
);

CREATE TABLE roommate_matches (
    match_id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    student_id             NUMBER NOT NULL,
    matched_student_id     NUMBER NOT NULL,
    match_score            NUMBER(5,2) NOT NULL,
    match_reason           VARCHAR2(300),
    matched_at             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_roommate_matches PRIMARY KEY (match_id),
    CONSTRAINT fk_rm_student FOREIGN KEY (student_id) REFERENCES users(user_id),
    CONSTRAINT fk_rm_matched_student FOREIGN KEY (matched_student_id) REFERENCES users(user_id),
    CONSTRAINT chk_rm_score CHECK (match_score BETWEEN 0 AND 100),
    CONSTRAINT chk_rm_not_same CHECK (student_id <> matched_student_id)
);

CREATE INDEX idx_users_role ON users(role_name);
CREATE INDEX idx_rooms_hall ON rooms(hall_id);
CREATE INDEX idx_seats_room_status ON seats(room_id, seat_status);
CREATE INDEX idx_bookings_status ON bookings(booking_status);
