CREATE TABLE roommate_match_result (
    match_id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    student_id           NUMBER NOT NULL,
    candidate_student_id NUMBER NOT NULL,
    match_score          NUMBER(5, 2) NOT NULL,
    match_reason         VARCHAR2(500),
    calculated_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_match_student FOREIGN KEY (student_id) REFERENCES app_user (user_id),
    CONSTRAINT fk_match_candidate FOREIGN KEY (candidate_student_id) REFERENCES app_user (user_id)
);

CREATE INDEX idx_match_student_score ON roommate_match_result (student_id, match_score DESC);

CREATE OR REPLACE PACKAGE pkg_roommate_matching AS
    FUNCTION get_match_score(
        p_student_id   NUMBER,
        p_candidate_id NUMBER
    ) RETURN NUMBER;

    PROCEDURE refresh_recommendations(
        p_student_id NUMBER
    );
END pkg_roommate_matching;
/

CREATE OR REPLACE PACKAGE BODY pkg_roommate_matching AS
    FUNCTION get_match_score(
        p_student_id   NUMBER,
        p_candidate_id NUMBER
    ) RETURN NUMBER IS
        v_score NUMBER := 0;
    BEGIN
        SELECT
              CASE WHEN NVL(a.department, 'NA') = NVL(b.department, 'NA') THEN 35 ELSE 0 END
            + CASE WHEN NVL(p1.preferred_department, a.department) = NVL(b.department, a.department) THEN 20 ELSE 0 END
            + CASE
                  WHEN p1.budget_min IS NOT NULL
                   AND p1.budget_max IS NOT NULL
                   AND b.monthly_budget BETWEEN p1.budget_min AND p1.budget_max
                  THEN 25 ELSE 0
              END
            + CASE WHEN NVL(p1.preferred_gender, 'ANY') = 'ANY' OR NVL(p1.preferred_gender, b.gender) = b.gender THEN 10 ELSE 0 END
            + CASE WHEN NVL(p1.prefers_quiet_room, 'N') = NVL(b.is_quiet, 'N') THEN 10 ELSE 0 END
        INTO v_score
        FROM app_user a
        JOIN roommate_preference p1 ON p1.student_id = a.user_id
        JOIN app_user b ON b.user_id = p_candidate_id
        WHERE a.user_id = p_student_id
          AND a.role_name = 'STUDENT'
          AND b.role_name = 'STUDENT';

        RETURN v_score;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN 0;
    END get_match_score;

    PROCEDURE refresh_recommendations(
        p_student_id NUMBER
    ) IS
    BEGIN
        DELETE FROM roommate_match_result
        WHERE student_id = p_student_id;

        INSERT INTO roommate_match_result (
            student_id,
            candidate_student_id,
            match_score,
            match_reason,
            calculated_at
        )
        SELECT
            p_student_id,
            c.user_id,
            get_match_score(p_student_id, c.user_id),
            'Department, budget, gender, and preference match',
            SYSTIMESTAMP
        FROM app_user c
        WHERE c.user_id <> p_student_id
          AND c.role_name = 'STUDENT';
    END refresh_recommendations;
END pkg_roommate_matching;
/
